FROM public.ecr.aws/lambda/python:3.8
WORKDIR /var/task
RUN mkdir lib/
COPY src/fn.py fn.py
COPY src/lib/customer.py lib/customer.py
COPY src/requirements.txt requirements.txt
RUN pip install -r requirements.txt
CMD [ "fn.handler" ]